export const MESSAGE = 'We couldn’t find this page.'
export const SEARCH_ENCOURAGEMENT = 'Maybe it’s out there, somewhere...'
export const HOMEPAGE_ENCOURAGEMENT = 'You can always find insightful stories on our'
export const HOMEPAGE_LABEL = 'homepage.'
export const SEARCH_LABEL = 'Search'